import "@/css/Home.css";
import "@/css/About.css";
import "@/css/projects.css";
import "@/css/resume.css";
import "@/css/shortcuts.css";
import "@/css/ContactMe.css";
import "@/css/ProjectInfo.css";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      
      <body className={inter.className}><div className="outerDiv">{children}</div></body>
    </html>
  )
}
